{"name": "test_login[输入错误账号B，密码，登陆]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'success!' == 'failed!'\n  - failed!\n  + success!", "trace": "test_input = {'password': '111111', 'username': 'xu'}, expeted = 'failed!'\n\n    @pytest.mark.parametrize(\"test_input,expeted\",test_datas,\n                             ids=[\"输入正确账号A，密码，登陆\",\n                                  \"输入错误账号B，密码，登陆\",\n                                  \"输入正确账号C，密码，登陆\"\n                                  ]\n                             )\n    def test_login(test_input,expeted):\n        \"\"\" 测试登陆用例\"\"\"\n        # 获取输入数据\n        # 获取函数返回结果\n        result = login(test_input[\"username\"],test_input[\"password\"])\n        # 断言\n>       assert result[\"msg\"] == expeted\nE       AssertionError: assert 'success!' == 'failed!'\nE         - failed!\nE         + success!\n\ntest_a_ids.py:67: AssertionError"}, "description": " 测试登陆用例", "attachments": [{"name": "stdout", "source": "9b99ec65-4a08-4899-a8a2-cd4a46e003f7-attachment.txt", "type": "text/plain"}], "start": 1653569175408, "stop": 1653569175409, "uuid": "34d26a98-f916-465a-a0b4-849a82dd09c5", "historyId": "12f7b88f0d6ceab0c8dfa6dbe37db8aa", "testCaseId": "c6e9f9edfaf5f438f333566498b79e9a", "fullName": "test_a_ids#test_login", "labels": [{"name": "suite", "value": "test_a_ids"}, {"name": "host", "value": "LAPTOP-IT6V6FE6"}, {"name": "thread", "value": "20916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_a_ids"}]}